name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            host: linux
            arch: gcc_64
            cmake_extra: ""
            build_dir: build
            artifact_name: NDEditor-linux-x86_64
            dist_path: build/rel/NDEditor.AppImage
          - os: windows-latest
            host: windows
            arch: win64_msvc2019_64
            cmake_extra: ""
            build_dir: build
            artifact_name: NDEditor-windows-x86_64
            dist_path: build/rel/Release/**
          - os: macos-latest
            host: mac
            arch: clang_64
            cmake_extra: "-DCMAKE_OSX_ARCHITECTURES=x86_64"
            build_dir: build
            artifact_name: NDEditor-macos-x86_64
            dist_path: build/rel/NDEditor.app.tar.gz

    steps:
      - uses: actions/checkout@v4
        name: Checkout source

      - name: Install Qt (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get update
          
          sudo apt-get update && sudo apt-get install -y \
              qtbase5-dev qtchooser qtbase5-dev-tools qtdeclarative5-dev \
              qtquickcontrols2-5-dev qtwebengine5-dev libglu1-mesa-dev libgl1-mesa-dev \
              libopengl-dev libfuse2 ninja-build libgtest-dev libqt5x11extras5-dev \
              build-essential qtcreator qttools5-dev libqt5opengl5-dev mesa-common-dev

          cmake --find-package -DNAME=Qt5OpenGLWidgets -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST
          
      # === macOS ===
      - name: Install Qt (macOS)
        if: runner.os == 'macOS'
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }} 
          version: 6.7.3
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          archives: "qtbase qttools qtcharts qtwebengine"
          cache: true

      # === Windows ===
      - name: Install Qt (Windows)
        if: runner.os == 'Windows'
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }}
          version: 6.7.3
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          archives: "qtbase qttools qtcharts qtwebengine"
          cache: false

      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja

      # 1) Debug + tests
      - name: Configure (Debug + tests)
        shell: bash
        run: |
          if [[ "$runner.os" == "Windows" ]]; then
            cmake -S . -B "${{ matrix.build_dir }}" \
              -G "Visual Studio 17 2019" -A x64 \
              -DCMAKE_BUILD_TYPE=Debug
          elif [[ "$runner.os" == "Linux" ]]; then
            cmake -S . -B "${{ matrix.build_dir }}" \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
              -DCMAKE_MODULE_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5/ \
              ${{ matrix.cmake_extra }}
          else
            cmake -S . -B "${{ matrix.build_dir }}" \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Debug \
              ${{ matrix.cmake_extra }}
          fi


      - name: Build tests
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake --build "${{ matrix.build_dir }}" --config Debug --target Test
          else
            cmake --build "${{ matrix.build_dir }}" --target Test
          fi

      - name: Run Google Tests
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./"${{ matrix.build_dir }}"/Debug/Test.exe --gtest_color=yes
          else
            ./"${{ matrix.build_dir }}"/Test --gtest_color=yes
          fi

      # 2) Release
      - name: Configure (Release)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake -S . -B "${{ matrix.build_dir }}/rel" \
              -G "Visual Studio 17 2019" -A x64 \
              -DCMAKE_BUILD_TYPE=Release
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            cmake -S . -B "${{ matrix.build_dir }}/rel" \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
              ${{ matrix.cmake_extra }}
          else
            cmake -S . -B "${{ matrix.build_dir }}/rel" \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              ${{ matrix.cmake_extra }}
          fi

      - name: Build NDEditor (Release)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake --build "${{ matrix.build_dir }}/rel" --config Release --target NDEditor
          else
            cmake --build "${{ matrix.build_dir }}/rel" --target NDEditor
          fi
          
      # 3) Deploy Qt libraries
      - name: Deploy Qt libraries (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          windeployqt "${{ matrix.build_dir }}/rel/Release/NDEditor.exe"

      - name: Deploy Qt libraries (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          macdeployqt "${{ matrix.build_dir }}/rel/NDEditor.app" -verbose=1
          tar -czf ${{ matrix.build_dir }}/rel/NDEditor.app.tar.gz -C ${{ matrix.build_dir }}/rel NDEditor.app

      - name: Deploy Qt libraries and create AppImage (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -euo pipefail
          set -x

          # Install prerequisites
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
            wget patchelf desktop-file-utils

          # Symlink Qt5 qmake explicitly (fixes qmake detection)
          sudo ln -sf /usr/lib/qt5/bin/qmake /usr/bin/qmake

          # Verify qmake points correctly (should show Qt5 version)
          qmake -v

          # Download linuxdeployqt (Qt5-compatible continuous build)
          LINUXDEPLOYQT=linuxdeployqt-continuous-x86_64.AppImage
          wget -qO "$LINUXDEPLOYQT" \
            https://github.com/probonopd/linuxdeployqt/releases/download/continuous/$LINUXDEPLOYQT
          chmod a+x "$LINUXDEPLOYQT"

          # Download appimagetool
          APPIMAGETOOL=appimagetool-x86_64.AppImage
          wget -qO "$APPIMAGETOOL" \
            https://github.com/AppImage/AppImageKit/releases/download/continuous/$APPIMAGETOOL
          chmod a+x "$APPIMAGETOOL"

          # Prepare AppDir
          BUILD_REL=build/rel
          APPDIR=$BUILD_REL/AppDir
          rm -rf "$APPDIR"
          mkdir -p \
            "$APPDIR/usr/bin" \
            "$APPDIR/usr/share/applications" \
            "$APPDIR/usr/share/icons/hicolor/256x256/apps"

          # Copy binary, .desktop file, and icon
          cp "$BUILD_REL/NDEditor" \
             "$APPDIR/usr/bin/"
          cp NDEditor.desktop \
             "$APPDIR/usr/share/applications/"
          cp images/app_icon.png \
             "$APPDIR/usr/share/icons/hicolor/256x256/apps/ndeditor.png"

          # Bundle Qt dependencies and build AppImage (using Qt5)
          export PATH="/usr/lib/qt5/bin:$PATH"
          ./"$LINUXDEPLOYQT" \
            "$APPDIR/usr/share/applications/NDEditor.desktop" \
            -appimage

          # Move resulting AppImage into rel folder
          mv NDEditor*.AppImage "$BUILD_REL/"
          mv "$BUILD_REL"/NDEditor-*-x86_64.AppImage "$BUILD_REL"/NDEditor.AppImage

            
      # 4) Upload from build/rel
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.dist_path }}
          if-no-files-found: error
