name: CI

on:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests (Debug, Linux x86‑64)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt & build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              qtbase5-dev qtchooser qtbase5-dev-tools qtdeclarative5-dev \
              qtquickcontrols2-5-dev qtwebengine5-dev libglu1-mesa-dev libgl1-mesa-dev \
              libopengl-dev libfuse2 ninja-build libgtest-dev libqt5x11extras5-dev \
              build-essential qtcreator qttools5-dev libqt5opengl5-dev mesa-common-dev

      - name: Configure Debug
        run: |
          cmake -S . -B build_dbg \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_PREFIX_PATH=/usr/lib/qt5

      - name: Build tests
        run: cmake --build build_dbg --target Test

      - name: Run Google Tests
        run: build_dbg/Test --gtest_color=yes

        
  build-and-package:
    runs-on: ${{ matrix.os }}
    needs: unit-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          # ===============================
          # 1) Linux (x86‑64)
          # ===============================
          - os: ubuntu-22.04
            host: linux
            arch: gcc_64
            cmake_extra: ""
            build_dir: build
            artifact_name: NDEditor-linux-x86_64
            dist_path: build/rel/NDEditor.AppImage

          # ===============================
          # 2) Linux (ARM64)
          # ===============================
          - os: ubuntu-22.04-arm
            host: linux
            arch: gcc_64           # Debian/Ubuntu arm64 packages share the same arch id
            cmake_extra: ""
            build_dir: build
            artifact_name: NDEditor-linux-arm64
            dist_path: build/rel/NDEditor.AppImage

          # ===============================
          # 3) Windows (x86‑64)
          # ===============================
          - os: windows-latest
            host: windows
            arch: win64_msvc2019_64
            cmake_platform: x64
            cmake_extra: ""
            build_dir: build
            artifact_name: NDEditor-windows-x86_64
            dist_path: build/rel/Release/**

          # ===============================
          # 4) Windows (ARM64) Cross-Compilation
          # ===============================
          - os: windows-latest
            host: windows
            arch: win64_msvc2019_arm64
            cmake_platform: ARM64
            cmake_extra: "-Thost=x64"
            build_dir: build
            artifact_name: NDEditor-windows-arm64
            dist_path: build/rel/Release/**

          # ===============================
          # 5) macOS Intel (x86‑64)
          # ===============================
          - os: macos-latest
            host: mac
            arch: clang_64
            cmake_extra: "-DCMAKE_OSX_ARCHITECTURES=x86_64"
            build_dir: build
            artifact_name: NDEditor-macos-x86_64
            dist_path: build/rel/NDEditor.app.tar.gz

          # ===============================
          # 6) macOS Apple Silicon (ARM64)
          # ===============================
          - os: macos-14
            host: mac
            arch: clang_64          # Universal package includes arm64 binaries
            cmake_extra: "-DCMAKE_OSX_ARCHITECTURES=arm64"
            build_dir: build
            artifact_name: NDEditor-macos-arm64
            dist_path: build/rel/NDEditor.app.tar.gz

          # ===============================
          # 7) android (ARM64)
          # ===============================
          - os: ubuntu-22.04          
            host: android             
            arch: android_arm64_v8a
            cmake_extra: >
              -DQT_ANDROID_BUILD=ON
              -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake
              -DANDROID_ABI=arm64-v8a
              -DANDROID_PLATFORM=android-24
            build_dir: build
            artifact_name: NDEditor-android-arm64
            dist_path: build/rel/Android/NDEditor.apk

    steps:
      - uses: actions/checkout@v4
        name: Checkout source

      # === Install Qt (Linux) ===
      - name: Install Qt (Linux)
        if: runner.os == 'Linux' && matrix.host == 'linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y \
              qtbase5-dev qtchooser qtbase5-dev-tools qtdeclarative5-dev \
              qtquickcontrols2-5-dev qtwebengine5-dev libglu1-mesa-dev libgl1-mesa-dev \
              libopengl-dev libfuse2 ninja-build libgtest-dev libqt5x11extras5-dev \
              build-essential qtcreator qttools5-dev libqt5opengl5-dev mesa-common-dev

      # === Install Qt (macOS/intel & apple‑silicon) ===
      - name: Install Qt (macOS)
        if: runner.os == 'macOS'
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }}
          version: 6.7.3
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          archives: "qtbase qttools qtcharts qtwebengine"
          cache: true

      - name: Install Qt host tools (x64) for ARM deploy
        if: ${{ runner.os == 'Windows' && matrix.arch == 'win64_msvc2019_arm64' }}
        id: qt_host
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }}
          version: 6.7.3
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          archives: "qtbase qttools"
          cache: true

      - name: Export QT_HOST_DIR
        if: ${{ runner.os == 'Windows' && matrix.arch == 'win64_msvc2019_arm64' }}
        shell: bash
        run: |
          echo "QT_HOST_WDEPLOY=$QT_HOST_PATH/bin/windeployqt.exe" >> "$GITHUB_ENV"

      # === Install Qt (Windows x86‑64 & arm64) ===
      - name: Install Qt (Windows x86‑64 / arm 64)
        if: runner.os == 'windows'
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }}
          version: 6.7.3
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          archives: "qtbase qttools qtcharts qtwebengine"
          cache: true

      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja

      - name: Set up Java (JDK 17)
        if: ${{ matrix.host == 'android' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK + NDK r26
        if: ${{ matrix.host == 'android' }}
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: "platform-tools build-tools;34.0.0 platforms;android-34"

      - name: Install Qt (Android)
        if: ${{ matrix.host == 'android' }}
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ runner.workspace }}
          version: 6.7.3
          host: linux
          target: android
          arch: android_arm64_v8a
          archives: "qtbase qttools qtcharts qtdeclarative qtquickcontrols2 qtwebengine"
          cache: true

      - name: Export Android env vars
        if: ${{ matrix.host == 'android' }}
        shell: bash
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME"       >> "$GITHUB_ENV"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_HOME"   >> "$GITHUB_ENV"

      - name: Check Qt CMake config files
        if: ${{ matrix.host == 'android' }}
        shell: bash
        run: |
          echo "QT_ROOT_DIR: $QT_ROOT_DIR"
          echo "Looking for Qt CMake config files under $QT_ROOT_DIR/lib/cmake"
          find "$QT_ROOT_DIR/lib/cmake" -type f \( \
            -iname "Qt6Config.cmake" -o \
            -iname "qt6-config.cmake" -o \
            -iname "Qt5Config.cmake" -o \
            -iname "qt5-config.cmake" \
          \) || echo "No matching config files found."

      # ---------------------------------------------------------------------
      # 1) Release build
      # ---------------------------------------------------------------------
      - name: Configure (Release)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake -S . -B "${{ matrix.build_dir }}/rel" \
              -G "Visual Studio 17 2022" -A ${{ matrix.cmake_platform }} \
              -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_extra }}
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            if [[ "${{ matrix.host }}" == "linux" ]]; then
              cmake -S . -B "${{ matrix.build_dir }}/rel" \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
                ${{ matrix.cmake_extra }}
            else
              cmake -S . -B "${{ matrix.build_dir }}/rel" \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR/lib/cmake/Qt6" \
                ${{ matrix.cmake_extra }}
            fi
          else
            cmake -S . -B "${{ matrix.build_dir }}/rel" \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              ${{ matrix.cmake_extra }}
          fi

      - name: Build NDEditor (Release)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake --build "${{ matrix.build_dir }}/rel" --config Release --target NDEditor
          else
            cmake --build "${{ matrix.build_dir }}/rel" --target NDEditor
          fi

      # ---------------------------------------------------------------------
      # 2) Deploy Qt libraries
      # ---------------------------------------------------------------------
      - name: Deploy Qt libraries (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          APP="${{ matrix.build_dir }}/rel/Release/NDEditor.exe"
          if [[ '${{ matrix.arch }}' == 'win64_msvc2019_arm64' ]]; then
             "$QT_HOST_WDEPLOY" \
              --qtpaths "$QT_ROOT_DIR/bin/qtpaths.bat" \
              "$APP"
          else
            windeployqt "$APP"
          fi

      - name: Deploy Qt libraries (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          macdeployqt "${{ matrix.build_dir }}/rel/NDEditor.app" -verbose=1
          tar -czf ${{ matrix.build_dir }}/rel/NDEditor.app.tar.gz -C ${{ matrix.build_dir }}/rel NDEditor.app

      - name: Deploy Qt libraries & create AppImage (Linux)
        if: runner.os == 'Linux' && matrix.host == 'linux'
        shell: bash
        run: |
          set -euo pipefail
          set -x

          sudo apt-get update
          sudo apt-get install -y libfuse2 wget patchelf desktop-file-utils imagemagick

          sudo ln -sf /usr/lib/qt5/bin/qmake /usr/bin/qmake
          qmake -v

          BUILD_REL=${{ matrix.build_dir }}/rel
          APPDIR=$BUILD_REL/AppDir
          rm -rf "$APPDIR"
          mkdir -p "$APPDIR/usr/bin" "$APPDIR/usr/share/applications" "$APPDIR/usr/share/icons/hicolor/256x256/apps"

          # Copy binary & desktop file
          cp "$BUILD_REL/NDEditor" "$APPDIR/usr/bin/"
          cp NDEditor.desktop "$APPDIR/usr/share/applications/"

          # Ensure we provide a 256×256 PNG icon (linuxdeploy fails on 1024×1024)
          ICON_SRC=images/app_icon.png
          ICON_DST="$APPDIR/usr/share/icons/hicolor/256x256/apps/ndeditor.png"
          convert "$ICON_SRC" -resize 256x256 "$ICON_DST"

          ARCH=$(uname -m)
          if [[ "$ARCH" == "aarch64" ]]; then
            LINUXDEPLOY=linuxdeploy-aarch64.AppImage
            QT_PLUGIN=linuxdeploy-plugin-qt-aarch64.AppImage
            wget -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/$LINUXDEPLOY" -O "$LINUXDEPLOY"
            wget -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/$QT_PLUGIN" -O "$QT_PLUGIN"
            chmod a+x "$LINUXDEPLOY" "$QT_PLUGIN"
            ."/$LINUXDEPLOY" --appdir "$APPDIR" --plugin qt --output appimage \
              --desktop-file "$APPDIR/usr/share/applications/NDEditor.desktop" \
              --icon-file "$ICON_DST"
          else
            LINUXDEPLOYQT=linuxdeployqt-continuous-x86_64.AppImage
            wget -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/$LINUXDEPLOYQT" -O "$LINUXDEPLOYQT"
            chmod a+x "$LINUXDEPLOYQT"
            ."/$LINUXDEPLOYQT" "$APPDIR/usr/share/applications/NDEditor.desktop" -appimage
          fi

          mv NDEditor*.AppImage "$BUILD_REL/"
          FIRST_APPIMG=$(ls build/rel/NDEditor*.AppImage | head -n1 || true)
          if [[ -n "$FIRST_APPIMG" ]]; then
              mv "$FIRST_APPIMG" build/rel/NDEditor.AppImage
          fi

      - name: Package APK with androiddeployqt
        if: ${{ matrix.host == 'android' }}
        shell: bash
        run: |
          set -euo pipefail
          BUILD_REL=${{ matrix.build_dir }}/rel
          androiddeployqt \
            --input  "$BUILD_REL/qt/android-deployment-settings.json" \
            --output "$BUILD_REL/Android" \
            --release \
            --gradle \
            --apk

      - name: Rename final APK
        if: ${{ matrix.host == 'android' }}
        shell: bash
        run: |
          BUILD_REL=${{ matrix.build_dir }}/rel
          APK=$(find "$BUILD_REL/Android" -name "*-release.apk" | head -n1)
          mkdir -p "$BUILD_REL/Android"
          mv "$APK" "${{ matrix.dist_path }}"

      # ---------------------------------------------------------------------
      # 3) Upload artefacts
      # ---------------------------------------------------------------------
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.dist_path }}
          if-no-files-found: error
